### ISSUE TITLE
Flicker (FOUC) when loading a site

### ISSUE THREAD

**Issue by MZ62** [hupe1980/gatsby-theme-material-ui#6]
Sites built with `gatsby build` flicker during loading/reloading.

**To reproduce**: Build one of your examples with `gatsby build` and serve them with `gatsby serve`. It flickers every time you load/reload it in the browser.

While it is probably barely (but clearly) visible in the small examples, it gets very flashy in larger sites I made.

I am using Chrome 76.0.3809.87, Windows 10.

**Comment by trevorblades** [comment]
This seems to be happening because the theme calls `wrapRootElement` in its Gatsby browser/ssr files, adding the `<ThemeProvider>` and `<CssBaseline>` components outside of the server rendering scope of `gatsby-plugin-material-ui`. [In the Gatsby/MUI example](https://github.com/mui-org/material-ui/tree/master/examples/gatsby), a custom `top-layout` plugin is used to add the `ThemeProvider` and `CssBaseline` before `gatsby-plugin-material-ui`, which results in the expected effect.

Ss far as I can tell, it's impossible for a theme to define and use a custom plugin prom its own `/plugins` directory. Maybe @ChristopherBiscardi can confirm this.

Maybe there's another way to wrap the root element before `gatsby-plugin-material-ui` gets a chance to do its own wrapping work... maybe a second theme made specifically for MUI theme injection?

1. User shadows `theme.js` from "core" theme

```js
// src/gatsby-theme-material-ui-core/theme.js
const {createMuiTheme} from '@material-ui/core';

const theme = createMuiTheme(...);

export default theme;
```

2. Second theme has a `gatsby-config.js` that looks like:

```js
plugins: [
  'gastby-theme-material-ui-core',
  'gastby-plugin-material-ui',
  ...others
]
```

I'm not certain that this will work, but I'm thinking that since it follows the same plugin order as shown in the Gatsby/MUI example, it's worth a try.

**Comment by ChristopherBiscardi** [comment]
> Ss far as I can tell, it's impossible for a Gatsby theme to define and use a custom plugin prom its own /plugins directory.

true. if you're using a theme it's already a plugin so there's no reason to have "local plugins of plugins"
